# Generated by Django 4.1.2 on 2022-11-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_extensionusuario_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
