# Generated by Django 4.1.2 on 2022-11-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_extensionusuario_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extensionusuario',
            name='fotos',
        ),
    ]
