# Generated by Django 4.1.1 on 2022-10-15 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='fecha_de_nacimiento',
        ),
        migrations.AddField(
            model_name='chef',
            name='apellido',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
