# Generated by Django 4.1.2 on 2022-11-03 00:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_chef_fecha_de_nacimiento_chef_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
