# Generated by Django 4.1.2 on 2022-11-05 15:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_chef_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
