# Generated by Django 4.1.2 on 2022-11-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_chef_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='chef',
            name='imagen_receta',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
