# Generated by Django 4.1.2 on 2022-11-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_chef_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
