# Generated by Django 4.1.2 on 2022-11-09 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_chef_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='fecha_creacion',
        ),
    ]
