# Generated by Django 4.1.2 on 2022-11-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_chef_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
