# Generated by Django 4.1.2 on 2022-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_chef_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='chef',
            name='imagen_receta',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
