# Generated by Django 4.1.2 on 2022-11-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_chef_fecha_creacion_alter_chef_imagen_receta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='imagen_receta',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
