# Generated by Django 4.1.2 on 2022-11-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_chef_imagen_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='chef',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
